[base]
HttpAddr = "localhost:3000"
RPCAddr = "localhost:3010"
[redis]
addr = "localhost:6379"
password = ""
db = 10
[etcd]
host = "localhost:2379"
basePath = "/im"
serverId = "1"
serverPath = "logicRpc"