[base]
RPCAddress = "localhost:3010"
[bucket]
num = 4
channelSize = 1024
roomSize = 1024
routineAmount = 32
routineSize = 20
[etcd]
host = "localhost:2379"
basePath = "/im"
serverPathComet = "cometRpc"
serverPathLogic = "logicRpc"
[websocket]
bind = "0.0.0.0:8911"
